const VNodeFlags = {
    ELEMENT_HTML: 1,
    ELEMENT_SVG: 1 << 1,
    COMPONENT_STATEFUL_NORMAL: 1 << 2,
    COMPONENT_STATEFUL_NEED_KEEP_ALIVE: 1 << 3,
    COMPONENT_STATEFUL_KEEP_ALIVE: 1 << 4,
    COMPONENT_FUNCTIONAL: 1 << 5,
    TEXT: 1 << 6,
    FRAGMENT: 1 << 7,
    PORTAL: 1 << 8
}

VNodeFlags.ELEMENT = VNodeFlags.ELEMENT_HTML | VNodeFlags.ELEMENT_SVG;
VNodeFlags.COMPONENT_STATEFUL =
    VNodeFlags.COMPONENT_STATEFUL_NORMAL |
    VNodeFlags.COMPONENT_STATEFUL_NEED_KEEP_ALIVE |
    VNodeFlags.COMPONENT_STATEFUL_KEEP_ALIVE;
VNodeFlags.COMPONENT = VNodeFlags.COMPONENT_STATEFUL | VNodeFlags.COMPONENT_FUNCTIONAL;

const ChildFlags = {
    NO_CHILDREN: 1,
    SINGLE_VNODE: 1 << 1,
    KEY_VODES: 1 << 2,
    NO_KEY_VODES: 1 << 3
}

ChildFlags.MULTIPLE_VNODES = ChildFlags.KEY_VODES | ChildFlags.NO_KEY_VODES;

export { VNodeFlags, ChildFlags }